### PR TITLE
Fix for duplicate cookie when using cookie domain option

### PR DESCRIPTION
**Pull request by coryodaniel**
See this issue: https://github.com/thoughtbot/clearance/issues/616

When using cookie domains two cookies were being sent to the browser:
1. a domain cookie
2. a regular cookie

Also, logging out would only the regular cookie to get deleted because the sign out method ignored if the domain was set. This would cause one cookie to still be set in the browser after log out, and create bizarre bouncy redirects when you logged in again (because the remember token was set the the previous session's remember token).

### CODE REVIEW

**Comment by derekprior** [comment]
@coryodaniel: Thanks for looking into this. These seems like really large changes and I have to admit I don't fully understand the problem right now. Is there any way you can either:

1. submit a failing test case, with no code changes, that describes the problem.
2. provide a link to a minimal reproduction application that I can play with.

When I have the time to do so, I'll probably try the 2nd one myself to better understand this, but that likely won't be for some time.

**Comment by coryodaniel** [comment]
@derekprior Hey I should be able to jump on this in a weekend or two. You can take a vanilla generated rails app and use the current version of clearance or 1.8.1 and the issue will occur. Its pretty much just turning on cookie domains. After that you'll see the cookie sent twice, given you are on 'www.example.com' you'll get a remember token for "www.example.com" and "example.com"

**Comment by coryodaniel** [comment]
Forgot all about this. Was it merged?

**Comment by MSchmidt** [comment]
Seems like this was closed but not merged? Not sure. Maybe @derekprior knows. Clearance 1.15.1 has same issue though.

**Comment by derekprior** [comment]
This is not merged. The best way to move forward would be a single failing test case or minimal reproduction sample app. At that point, I'll better understand the issue and hopefully be able to provide some guidance on what I think the best change would be in a way that limits the scope as much as possible.

Thanks.

**Comment by MSchmidt** [comment]
I've posted a reproduction sample app to #616. Hope this helps.

**Pull request closed without merging**
