### PR TITLE
Stop specifying a range of copyright years

### PR DESCRIPTION
**Pull request by derekprior**
The date of firts publication seems sufficient and it prevents us from having
to update a range of years every year.

### CODE REVIEW

**Comment by sikachu** [comment]
:copyright:

**Comment by gfontenot** [comment]
oh god yes can we do this everywhere?

**Comment by calebthompson** [comment]
:+1:

**Comment by JoelQ** [comment]
Down with date ranges! Next step, specify all the years individually like gnu.org :wink: 
the gnu operating system 2015-01-08 10-31-23

**Comment by gabebw** [comment]
Typo: firts

**Comment by gabebw** [comment]
Oh it's fixed in the actual commit.

**Comment by gabebw** [comment]
:+1:

**Comment by derekprior** [comment]
Merged in d372ebd3adbb646dea2822c25d1530da5bc36c5f

**Pull request closed without merging**
