### PR TITLE
Test against rails 7.1

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
I.... don't know why CI is failing this way only on 7.1, it looks like the db reset isn't creating tables?

**Comment by sej3506** [comment]
Hey, @segiddins! I spent some time digging into the CI failures with some co-workers. The solution is not totally nailed down yet, but we're on the right track. It appears there may be an issue with how the table(s) are being created. Like you noticed, `dummy:db:reset` isn't doing what it should be doing. When we ran the commands separately, `dummy:db:drop` `dummy:db:create` `dummy:db:migrate`, we had more success.

There's still some issue with the migration generation, but again, feeling like the solution is on its way.

Hope to unblock you within the next week. :)

**Comment by sej3506** [comment]
@segiddins I need to clean up my own PR's commit message and all before I merge it (https://github.com/thoughtbot/clearance/pull/998) but I've rebased your changes on top here so now we can see those pretty pretty green lights.

**Comment by segiddins** [comment]
Amazing, thanks so much for the help @sej3506! Super excited to get this into RubyGems.org

**Comment by segiddins** [comment]
@sej3506 i think you might've force-pushed over my last commit or two

**Comment by sej3506** [comment]
@segiddins I sincerely apologize. I definitely should not have been force pushing (especially on someone else's branch). If you have the commits locally still, you can add them to the branch using [this method](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/commit-exists-on-github-but-not-in-my-local-clone#the-branch-that-contained-the-commit-was-deleted).

If you do not have them locally anymore, I can add them back manually using the information [here](https://github.com/thoughtbot/clearance/commit/b34dc2fb57171c684fce4d01d76aa1a1d9d4d421) and [here](https://github.com/thoughtbot/clearance/commit/985780f08380acce5c6addf7adb8a8f51639b3f7).

**Comment by segiddins** [comment]
All good! I added it back

**Comment by segiddins** [comment]
@sej3506 I think this should be ready to merge & release whenever y'all are ready!

**Review by sej3506 — APPROVED** [review]
👍🏻 Thank you!

**Comment by segiddins** [comment]
if it's not too much of a hassle, a release with this would be :100: 🙇🏻‍♂️

**Comment by simi** [comment]
@sej3506 anything I can help with to get release done?

**Comment by sej3506** [comment]
@segiddins @simi Sorry for the delay on this release. It's out now!

**Pull request merged**
