### PR TITLE
Remove duplicate controller spec

### PR DESCRIPTION
**Pull request by pedrosmmoreira**
This file - `spec/clearance/contoller_spec.rb` - seems to be a left over duplicate of `spec/clearance/controller_spec.rb` and can be safely removed.

### CODE REVIEW

**Comment by derekprior** [comment]
I don't follow the PR description here as you list the same file twice. I've search the body of the spec you propose deleting and don't see it anywhere.

This spec ensures that `Clearance::Controller` does not leak action methods and was introduced in f518f65973616f3b88c2b55dd02386862ae70682.

Closing for now, but please continue the conversation if you think this is in error. Thanks.

**Comment by pedrosmmoreira** [comment]
@derekprior, apologies for lack of clarity in the PR description. In 'spec/clearance/controllers' there is a 'contoller_spec' file that duplicates the contents of 'controller_spec' (found in the same dir). This PR proposes removing 'contoller_spec' and keeping 'controller_spec'.

Hope this makes it clearer :)

**Comment by derekprior** [comment]
Ahhhhhh yes. I see now.

**Comment by derekprior** [comment]
Merged in 754bc8a0afe709150737312a62c799eeac014c02

**Pull request closed without merging**
