### PR TITLE
switch from travis to github actions

### PR DESCRIPTION
**Pull request by gingerlime**
* converted from .travis.yml
* removed .travis.yml

### CODE REVIEW

**Comment by gingerlime** [comment]
unfortunately the rails 6.0 tests are failing, but I'm not really sure why. See https://github.com/gingerlime/clearance/actions/runs/473819643

**Comment by gingerlime** [comment]
looks like travis also fails with rails 6.0 https://travis-ci.org/github/thoughtbot/clearance/builds/753660714

**Comment by eebs** [comment]
Thank you @gingerlime this is fantastic. The last Travis run for a different PR took over 2 hours to complete, it looks like with GitHub Actions they all run collectively in under 2 minutes. 🎉 

I think because it's a PR the actions are running on your fork and not showing here, but I assume once this is merged they'll appear within this repo. There was one [failure](https://github.com/gingerlime/clearance/runs/1710763973?check_suite_focus=true) but I believe this to be unrelated to this PR so I'm going to go ahead and merge this.

Thanks again for taking the time to improve Clearance!

**Comment by gingerlime** [comment]
My pleasure, @eebs 👍

**Pull request merged**
