### PR TITLE
Add expiring, databaseless password reset tokens (alternative solution)

### PR DESCRIPTION
**Pull request by ignatiusreza**
Hi guys! I saw that #682 got stale and with #817 on the way, I thought that it's a good time to try to revive this effort..

This PR is a rebased of #682, with extra changes on top to address the concern related to `the risk of exposing the existing encrypted password`..

In summary, the differences between this PR and #682 is, in this PR reset token are generated using `ActiveSupport::MessageEncryptor` instead of `ActiveSupport::MessageVerifier`..

As can be seen from the [module documentation](https://github.com/rails/rails/blob/v5.2.2/activesupport/lib/active_support/message_encryptor.rb#L11-L12), `ActiveSupport::MessageEncryptor` is designed as `a simple way to encrypt values which get stored somewhere you don't trust.`, which perfectly fit our needs..

As part of the changes, I introduces a new class `Clearance::Tokenizer` to wrap the logic around `ActiveSupport::MessageEncryptor` and changes the configuration option from `configuration.message_verifier` to `configuration.tokenizer`.. I think, in the long term, we could somehow merge `Clearance::Token` and `Clearance::Tokenizer` (or delegate token generation logic inside `Clearance::Token` to `Clearance::Tokenizer`)..

### CODE REVIEW

**Comment by ignatiusreza** [comment]
btw, rubocop is complaining quite a lot even for existing codes.. so i'm a little bit confused as to which style/guideline to follow?

**Comment by ignatiusreza** [comment]
@mjankowski I'm sorry, do you mind sharing the reason why this PR is closed? I hope i didn't step on anyone's toes.. 🙇‍♂️

**Comment by mjankowski** [comment]
I have no idea how that happened.

**Comment by ignatiusreza** [comment]
Okay, that's odd.. 🤔 is it okay to get this reopened then? Or is there no longer any interest for this feature?

**Comment by mjankowski** [comment]
I figured it out ... while I did not actively close this PR, I did delete the branch that this PR had been against, which had the side effect of closing this PR! Sorry about that.

I'm not actually able to re-open this ... but if you want to re-open against master we can review it again.

**Comment by ignatiusreza** [comment]
Sure, no problem.. i'll rebase against master and will open a new PR.. thanks for investigating!

**Comment by ignatiusreza** [comment]
PR reopened at #834

**Pull request closed without merging**
