### PR TITLE
Allow vendorizing of gems

### PR DESCRIPTION
**Pull request by imtayadeway**
I needed [this fix](https://github.com/thoughtbot/appraisal/commit/91eb5d63fdbc7237c6e1715b5569ac85a727a5d6) in order to get up and running, so I upgraded to the latest appraisal. Not sure if this was being held back for a specific reason?

/cc @derekprior 

Thanks!

### CODE REVIEW

**Comment by imtayadeway** [comment]
Looks like I missed that this would cause an issue with Ruby 1.9.3. Was this why appraisal was restricted to version 1?

**Comment by thiagoa** [comment]
@imtayadeway I've had this same error with my build, looks like it was already on master.

**Comment by imtayadeway** [comment]
@thiagoa funny seeing you here! :grin: Thanks for the info! I haven't had time to look into the failure but will try to soon.

**Comment by thiagoa** [comment]
@imtayadeway Yep, sorry for the out of the blue intervention. Actually, I saw a notification and thought my comment had something to add :)

**Comment by derekprior** [comment]
Merged as a7d1da122dda9ceee256f94c661cd9cd4198acc6. Thanks!

**Comment by imtayadeway** [comment]
:heart:

**Pull request closed without merging**
